# Generated by Django 6.0.4 on 2026-04-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wykaz_filmow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='ocena',
            new_name='film',
        ),
    ]
