# Generated by Django 6.0.4 on 2026-04-19 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wykaz_filmow', '0002_rename_ocena_ocena_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
