# Generated by Django 6.0.4 on 2026-04-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wykaz_filmow', '0003_ocena_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='rezyser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wykaz_filmow.rezyser'),
        ),
    ]
