# Generated by Django 6.0.4 on 2026-04-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wykaz_filmow', '0004_rezyser_film_rezyser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezyser',
            options={'verbose_name_plural': 'Reżyserzy'},
        ),
    ]
